//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------

using Terminal.Gui;

namespace ChoiceEngine1
{

    public partial class PlayerName
    {
        public PlayerName()
        {
            InitializeComponent();
            button.Text = "¡DONE!";
            button.Clicked += () =>
            {
                if (playerName.Text.ToString() == "")
                {
                    Application.RequestStop();
                }
                else
                {
                    DecisionController.Player.Name = playerName.Text.ToString();
                    Application.RequestStop();
                }
            };
        }
    }
}